stages:
  genetics_to_yaml_file:
    cmd: poetry run parse_xml --type=genetics 10
    params:
    - params/data.yaml:
      - paths.genetics
    deps:
    - data/raw/genetics
    - src/data/process.py
    - src/data/utils/_parse_xml.py
    - src/data/utils/base.py
    - src/data/utils/types.py
    outs:
    - data/interim/genetics/data.yaml
